---
title: Short Paper
author:
  - name: Alice Anonymous
    email: alice@example.com
    affiliation: Some Institute of Technology
    footnote: Corresponding Author
  - name: Bob Security
    email: bob@example.com
    affiliation: Another University
address:
  - code: Some Institute of Technology
    address: Department, Street, City, State, Zip
  - code: Another University
    address: Department, Street, City, State, Zip
abstract: |
  This is the abstract.

  It consists of two paragraphs.

journal: "An awesome journal"
date: "`r Sys.Date()`"
bibliography: mybibfile.bib
output: rticles::elsevier_article
---




# Introduction

The primary objective of this paper is to develop a low-cost system that can record and categorize track flows through residential neighborhoods. 

# Methods
To motivate this we provide an example of using repeat photography to classify images of a roadway for the presence of FedEx trucks and buses using TensorFlow, and then demonstrate ways to analyze traffic based on labeled images. 

## AOI Selection
Although not critical for sucess in this case, many classification tasks can be improved by restricting the field of view to the area of interest (AOI) that contains the most informative components of an image. In this case any components of the image above the roadway provide no substantive information for the classification task and might throw off the classifier through uninformative changes in lighting, phenology across seasons, or changes in camera placement. 

To minimize these issues we apply a multi-stage process to first identify the roadway, then mask out unnessesary image elements. In the first stage, we identify and isolate 
the yellow road centerline using color selection. 

yellow line image

Then yellow lines are then coverted to greyscale, and smoothed. These smoothed lines can then be used with a Canny Edge Detector [@ reference]. 

grey scale smoothed image

 Edges can be defined as the boundary between an object and its background. In its most basic form edge detectors, like Sobel filters, use kernals (moving windows) to calculate the difference between adjacent pixels in both the X and Y axis. High gradient values can be treated as lines, and low gradient values are dropped from consideration. Canny edge detection [@ 1986 ] goes a few steps further to try to isolate the strongest and most continuous lines. In canny, edges detected by the Sobel kernals are then thinned to be one pixel wide, and then filtered by histeresis thresholding. Each line is scored by its strength relative to neighboring lines. Then to avoid noise or non-continuous edges, Histeresis thresholding is applied to return only the most prominent and continuous lines. Thresholds are chosen between the values of zero (no edge) and two fifty five (sharp edge). Two thresholds are chosen manually, the first, where all edges with values less than the minimum threshold are dropped completely from consideration. The second upper threshold is more complex, edges with values above the upper threshold are always included, but edges with thresholds between the minimum and maximum thresholds are only included if they touch a line that is above the maximum threshold. As result canny edge detection flexibly identifies strong and continuous lines, while removing ones that are potenitally the result of noise or are weak and non-continuous. https://www.youtube.com/watch?v=sRFM5IEqR2w

canny example

## Tensor Classifier


# Results 

# Discussion



_Text based on elsarticle sample manuscript, see [http://www.elsevier.com/author-schemas/latex-instructions#elsarticle](http://www.elsevier.com/author-schemas/latex-instructions#elsarticle)_


The Elsevier article class
==========================

#### Installation

If the document class *elsarticle* is not available on your computer,
you can download and install the system package *texlive-publishers*
(Linux) or install the LaTeX package *elsarticle* using the package
manager of your TeX installation, which is typically TeX Live or MikTeX.

#### Usage

Once the package is properly installed, you can use the document class
*elsarticle* to create a manuscript. Please make sure that your
manuscript follows the guidelines in the Guide for Authors of the
relevant journal. It is not necessary to typeset your manuscript in
exactly the same way as an article, unless you are submitting to a
camera-ready copy (CRC) journal.

#### Functionality

The Elsevier article class is based on the standard article class and
supports almost all of the functionality of that class. In addition, it
features commands and options to format the

-   document style

-   baselineskip

-   front matter

-   keywords and MSC codes

-   theorems, definitions and proofs

-   lables of enumerations

-   citation style and labeling.

Front matter
============

The author names and affiliations could be formatted in two ways:

(1) Group the authors per affiliation.

(2) Use footnotes to indicate the affiliations.

See the front matter of this document for examples. You are recommended
to conform your choice to the journal you are submitting to.

Bibliography styles
===================

There are various bibliography styles available. You can select the
style of your choice in the preamble of this document. These styles are
Elsevier styles based on standard styles like Harvard and Vancouver.
Please use BibTeX to generate your bibliography and include DOIs
whenever available.

Here are two sample references: @Feynman1963118 [@Dirac1953888].

References {#references .unnumbered}
==========
